kind: pipeline
type: docker
name: test-memprof-develop

steps:
  - name: memprof-build
    image: simplestakingcom/tezedge-bpf-builder:latest
    commands:
      - apt-get install -y pkg-config libssl-dev
      - cargo install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch main
      - cargo build -p bpf-memprof --release && cargo build -p tezedge-memprof --tests --release
  - name: memprof-run
    image: simplestakingcom/tezedge-bpf-builder:latest
    detach: true
    privileged: true
    volumes:
      - name: kernel-debug
        path: /sys/kernel/debug
    commands:
      - apt-get install -y libelf-dev
      - ./target/none/release/bpf-memprof-user & sleep 0.5 && ./target/none/release/tezedge-memprof &
  - name: tezedge-node
    image: simplestakingcom/tezedge:latest
    detach: true
    commands:
      - sleep 10 # wait while previous step install libelf-dev
      - ./light-node --config-file=/tezedge.config --p2p-port=9732 --rpc-port=18732 --websocket-address=0.0.0.0:4927 --init-sapling-spend-params-file=/sapling-spend.params --init-sapling-output-params-file=/sapling-output.params
  - name: memprof-test
    image: simplestakingcom/tezedge-bpf-builder:latest
    commands:
      - sleep 30 && URL=http://localhost:17832 cargo test -p tezedge-memprof --release -- --nocapture || exit 101
      - sleep 30 && URL=http://localhost:17832 cargo test -p tezedge-memprof --release -- --nocapture || exit 101
      - sleep 30 && URL=http://localhost:17832 cargo test -p tezedge-memprof --release -- --nocapture || exit 101

volumes:
  - name: kernel-debug
    host:
      path: /sys/kernel/debug

---

kind: pipeline
name: docker-deploy-memprof-develop

steps:
  - name: build-tezedge-memprof-image  
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-memprof
      tag: latest
      dockerfile: Dockerfile.memprof
      build_args:
        - TEZEDGE_IMAGE=simplestakingcom/tezedge:latest
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

depends_on:
  - test-memprof-develop

trigger:
  branch: develop
  event: push
