kind: pipeline
name: docker-deploy-develop

# TODO: tests

steps:
- name: build-tezedge-debugger-image  
  image: plugins/docker
  settings:
    repo: simplestakingcom/tezedge-debugger
    tag: latest
    dockerfile: Dockerfile
    build_args:
      - BRANCH=develop
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_pswd

trigger:
  branch: develop
  event: push
