kind: pipeline
type: docker
name: default

steps:
  - name: set_server_identity
    image: ubuntu
    pull: if-not-exists
    volumes:
      - name: server-identity
        path: /tmp/volume
    commands:
      - cp ./tests/server_identity.json /tmp/volume/identity.json
  - name: set_client_identity
    image: ubuntu
    pull: if-not-exists
    volumes:
      - name: client-identity
        path: /tmp/volume
    commands:
      - cp ./tests/client_identity.json /tmp/volume/identity.json
  - name: build
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    environment:
      RUST_BACKTRACE: 1
    volumes:
      - name: binaries
        path: /tmp/binaries
    commands:
      - cargo install --bins --path . --root .
      - cp ./bin/* /tmp/binaries
  - name: server
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    environment:
      DEBUGGER: "FALSE"
    detach: true
    volumes:
      - name: binaries
        path: /etc/bin
      - name: server-identity
        path: /tmp/volume
    commands:
      - /etc/bin/drone-server &
      - /etc/bin/tezedge-debugger
  - name: client
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    environment:
      DEBUGGER_URL: "http://server:13031"
      DEBUGGER: "FALSE"
    volumes:
      - name: binaries
        path: /etc/bin
      - name: client-identity
        path: /tmp/volume
    commands:
      - /etc/bin/tezedge-debugger &
      - sleep 2
      - /etc/bin/drone-client --server server:13030
      - cargo test

volumes:
  - name: binaries
    temp: {}
  - name: server-identity
    temp: {}
  - name: client-identity
    temp: {}

trigger:
  branch:
    - master
    - dev