kind: pipeline
type: docker
name: debugger-tests

steps:
  - name: debugger
    image: simplestakingcom/tezedge-debugger:5.11
    privileged: true
    volumes:
      - name: tezos-shared-data
        path: /tmp/volume/tezos
      - name: kernel-debug
        path: /sys/kernel/debug
    environment:
      RUST_BACKTRACE: 1
    commands:
      - apt update && apt install -y curl
      - cp /etc/config-drone.toml config.toml
      - bpf-sniffer & sleep 0.5 && tezedge-recorder &
      - URL="tezos-node:18733/chains/main/blocks/head" timeout 60 wait_until.sh
      - sleep 10 && DEBUGGER_URL="localhost:17743" tester

services:
  - name: tezos-node
    image: tezos/tezos:v8.1
    volumes:
      - name: tezos-shared-data
        path: /var/run/tezos/node
    commands:
      - sleep 5 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*' --rpc-addr=[::]:18733 --net-addr=[::]:9733 --history-mode archive

volumes:
  - name: tezos-shared-data
    temp: {}
  - name: kernel-debug
    host:
      path: /sys/kernel/debug

---

kind: pipeline
name: docker-deploy-develop

steps:
  - name: build-tezedge-debugger-image  
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-debugger
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

trigger:
  branch: develop
  event: push

#depends_on:
#  - build-and-tests

---

kind: pipeline
name: docker-deploy-release

steps:
  - name: build-tezedge-debugger-image
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-debugger
      tags: 
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

trigger:
  ref: refs/tags/**
  event: tag

#depends_on:
#  - build-and-tests
