kind: pipeline
type: docker
name: test-memprof

steps:
  - name: unit-tests
    image: simplestakingcom/tezedge-bpf-builder:latest
    commands:
      - apt-get install -y pkg-config libssl-dev
      - cargo install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch main
      - cargo test --package tezedge-memprof --lib -- history::history
      - cargo test --package tezedge-memprof --lib -- history::tests
  - name: memprof-compare-test
    image: simplestakingcom/tezedge-bpf-builder:latest
    privileged: true
    volumes:
      - name: kernel-debug
        path: /sys/kernel/debug
      - name: proc-dir
        path: /proc
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - apt-get install -y pkg-config libssl-dev curl
      # docker client
      - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-20.10.0.tgz
      - tar xzf docker-20.10.0.tgz --strip 1 -C /usr/local/bin docker/docker
      - rm docker-20.10.0.tgz
      # build and run memprof
      - cargo install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch main
      - cargo build -p bpf-memprof --release && cargo build -p tezedge-memprof --tests --release
      - ./target/none/release/bpf-memprof-user & sleep 0.5 && ./target/none/release/tezedge-memprof & sleep 0.5
      # run tezedge-node in docker
      - export NODE_CONTAINER=$(docker run --rm -d simplestakingcom/tezedge:latest-frame-pointers-enabled --network mainnet)
      # do tests
      - URL=http://localhost:17832 cargo test -p tezedge-memprof --release -- positive compare --nocapture
      # stop the node
      - docker stop $NODE_CONTAINER

volumes:
  - name: kernel-debug
    host:
      path: /sys/kernel/debug
  - name: proc-dir
    host:
      path: /proc
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---

kind: pipeline
name: docker-deploy-develop

steps:
  - name: build-tezedge-debugger-image  
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-debugger
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd
  - name: build-tezedge-memprof-image  
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-memprof
      tag: latest
      dockerfile: Dockerfile.memprof
      build_args:
        - TEZEDGE_IMAGE=simplestakingcom/tezedge:latest-frame-pointers-enabled
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

depends_on:
  - test-memprof

trigger:
  branch: develop
  event: push

---

kind: pipeline
name: docker-deploy-release

steps:
  - name: build-tezedge-debugger-image
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-debugger
      tags: 
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd
  - name: build-tezedge-memprof-image  
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-memprof
      tag: latest-release
      dockerfile: Dockerfile.memprof
      build_args:
        - TEZEDGE_IMAGE=simplestakingcom/tezedge:latest-frame-pointers-enabled-release
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

depends_on:
  - test-memprof

trigger:
  ref: refs/tags/**
  event: tag
