kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    environment:
      RUST_BACKTRACE: 1
    volumes:
      - name: binaries
        path: /tmp/binaries
    commands:
      - cargo install --bins --path . --root .
      - cp ./bin/* /tmp/binaries
  - name: server
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    detach: true
    volumes:
      - name: binaries
        path: /etc/bin
      - name: identity
        path: /tmp/volume
    commands:
      - /etc/bin/drone-server &
      - /etc/bin/tezedge-debugger
  - name: client
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    volumes:
      - name: binaries
        path: /etc/bin
    commands:
      - sleep 1
      - /etc/bin/drone-client --server server:13030
      - sleep 1
#  - name: test
#    image: simplestakingcom/tezedge-ci-builder:latest
#    pull: if-not-exists
#    volumes:
#      - name: binaries
#        path: /etc/bin
#    commands:
#      - /etc/bin/enpoint-tester http://server:13031/v2/p2p 2

volumes:
  - name: binaries
    temp: {}
  - name: identity
    host:
      path: /tmp/volume