kind: pipeline
type: docker
name: test-memprof

steps:
  - name: test-memprof
    image: tezedge/tezedge-bpf-builder:latest
    privileged: true
    volumes:
      - name: kernel-debug
        path: /sys/kernel/debug
      - name: proc-dir
        path: /proc
      - name: docker_sock
        path: /var/run/docker.sock
      - name: tmp_dir
        path: /tmp
    commands:
      - apt-get update
      - DEBIAN_FRONTEND='noninteractive' apt-get install -y git wget curl gcc libsodium-dev make zlib1g-dev lsb-release software-properties-common pkg-config clang libev-dev g++ libssl-dev libelf-dev
      - wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
      - chmod +x rustup-init
      - ./rustup-init -y --no-modify-path --default-toolchain nightly-2022-04-15
      - rm rustup-init*
      - export PATH=/root/.cargo/bin:$PATH
      - rustup update stable
      - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 12 && rm llvm.sh
      # docker client
      # - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-20.10.0.tgz
      # - tar xzf docker-20.10.0.tgz --strip 1 -C /usr/local/bin docker/docker
      # - rm docker-20.10.0.tgz
      # build memprof
      - cargo +stable install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch develop
      - cargo +stable test --package tezedge-memprof --lib --release -- history::history history::tests
      - cargo +stable build -p bpf-memprof --release
      - cargo +stable build -p tezedge-memprof --tests --release
      # run tezedge-node in docker
      # - docker stop tezedge_node || true
      # - TEZEDGE_NODE_NAME=tezedge_node ./target/none/release/bpf-memprof-user &
      # - docker run --rm -d --name tezedge_node tezedge/tezedge:latest-frame-pointers-enabled --network hangzhounet
      # do tests
      # - URL=http://localhost:17832 cargo +nightly-2021-03-23 test -p tezedge-memprof --release -- positive compare --nocapture
      # stop the node
      # - docker stop tezedge_node

volumes:
  - name: kernel-debug
    host:
      path: /sys/kernel/debug
  - name: proc-dir
    host:
      path: /proc
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: tmp_dir
    host:
      path: /tmp

---

kind: pipeline
type: docker
name: test-recorder

steps:
  - name: test-recorder
    image: ubuntu:20.04
    privileged: true
    volumes:
      - name: tezedge-shared-data
        path: /tmp/volume
      - name: kernel-debug
        path: /sys/kernel/debug
    commands:
      - apt-get update
      - DEBIAN_FRONTEND='noninteractive' apt-get install -y git wget curl gcc libsodium-dev make zlib1g-dev lsb-release software-properties-common pkg-config clang libev-dev g++ libssl-dev libelf-dev
      - wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
      - chmod +x rustup-init
      - ./rustup-init -y --no-modify-path --default-toolchain nightly-2022-04-15
      - rm rustup-init*
      - export PATH=/root/.cargo/bin:$PATH
      - rustup update stable
      - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 12 && rm llvm.sh
      # build recorder
      - cargo +stable install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch develop
      - cargo +stable install --path bpf-recorder
      - cargo +stable build -p tezedge-recorder --tests --release
      # prepare
      - mkdir -p target/debugger_db || true
      # test
      - ./tezedge-recorder/test.sh

volumes:
  - name: tezedge-shared-data
    host:
      path: /tmp/volume
  - name: kernel-debug
    host:
      path: /sys/kernel/debug

---

kind: pipeline
name: docker-deploy-develop

steps:
  - name: build-tezedge-debugger-image  
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-debugger
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd
  - name: build-tezedge-memprof-image  
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-memprof
      tag: latest
      dockerfile: Dockerfile.memprof
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

depends_on:
  - test-memprof
  - test-recorder

trigger:
  branch: develop
  event: push

---

kind: pipeline
name: docker-deploy-release

steps:
  - name: build-tezedge-debugger-image
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-debugger
      tags: 
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd
  - name: build-tezedge-memprof-image  
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-memprof
      tags: 
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile.memprof
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

depends_on:
  - test-memprof
  - test-recorder

trigger:
  ref: refs/tags/**
  event: tag
