kind: pipeline
type: docker
name: debugger-tests

steps:
  - name: debugger-tester
    image: simplestakingcom/tezedge-bpf-builder:latest
    pull: if-not-exists
    commands:
      - apt install -y g++
      - git clone https://github.com/tezedge/tezedge-debugger && cd tezedge-debugger && git checkout memprof
      - URL="tezos-node:18733/chains/main/blocks/head" timeout 60 ./tests/wait_until.sh
      - DEBUGGER_URL="debugger:17743" cargo test -p tester

services:
  - name: debugger
    image: simplestakingcom/tezedge-debugger:5.11
    privileged: true
    volumes:
      - name: tezos-shared-data
        path: /tmp/volume/tezos
      - name: config
        path: /home/appuser/config.toml
      - name: kernel-debug
        path: /sys/kernel/debug
    environment:
      RUST_BACKTRACE: 1
    commands:
      - cd /home/appuser
      - ./bpf-sniffer & sleep 0.5
      - ./tezedge-recorder
  - name: tezos-node
    image: tezos/tezos:v8.1
    volumes:
      - name: tezos-shared-data
        path: /var/run/tezos/node
    commands:
      - sleep 5 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*' --rpc-addr=[::]:18733 --net-addr=[::]:9733 --history-mode archive

volumes:
  - name: tezos-shared-data
    temp: {}
  - name: config
    host:
      path: /var/lib/docker/volumes/remote-workspace/_data/tezedge-debugger/config-drone.toml
  - name: kernel-debug
    host:
      path: /sys/kernel/debug
