kind: pipeline
type: docker
name: build-and-tests

steps:
  - name: build
    image: simplestakingcom/tezedge-bpf-builder:latest
    pull: if-not-exists
    environment:
      RUST_BACKTRACE: 1
    volumes:
      - name: binaries
        path: /tmp/binaries
    commands:
      - apt install -y g++
      - cargo install --bins --path . --root . tezedge_debugger
      - cp bin/* /tmp/binaries
      - cp tests/wait_until.sh /tmp/binaries
  - name: test-with-ocaml-node
    image: ubuntu:20.04
    privileged: true
    volumes:
      - name: binaries
        path: /tmp/binaries
      - name: data
        path: /tmp/volume
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - apt update && apt install -y curl jq
      - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-20.10.0.tgz
      - tar xzf docker-20.10.0.tgz --strip 1 -C /usr/local/bin docker/docker
      - rm docker-20.10.0.tgz
      - export NODE_CONTAINER=$(docker run --rm -p 18732:18732 -v /tmp/volume:/var/run/tezos/node:rw -dt --entrypoint sh tezos/tezos:v7.0 -c "sleep 5 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*' --rpc-addr=[::]:18732 --net-addr=[::]:9732")
      - P2P_PORT=9732 /tmp/binaries/tezedge-debugger &
      - timeout 60 /tmp/binaries/wait_until.sh
      - docker stop $NODE_CONTAINER
      # TODO: here debugger should has enough values, execute tests

volumes:
  - name: binaries
    temp: {}
  - name: data
    temp: {}
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
    - develop
  event: push

---

kind: pipeline
name: docker-deploy-develop

steps:
  - name: build-tezedge-debugger-image  
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-debugger
      tag: latest
      dockerfile: Dockerfile
      build_args:
        - branch=develop
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

trigger:
  branch: develop
  event: push

depends_on:
  - build-and-tests

---

kind: pipeline
name: docker-deploy-release

steps:
  - name: build-tezedge-debugger-image
    image: plugins/docker
    settings:
      repo: simplestakingcom/tezedge-debugger
      tags: 
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile
      build_args:
        - branch=master
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

trigger:
  ref: refs/tags/**
  event: tag

depends_on:
  - build-and-tests
