[package]
name = "tezedge_debugger"
version = "0.1.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tezedge-debugger"
path = "src/bin/debugger.rs"

[[bin]]
name = "drone-server"
path = "src/bin/drone_test_server.rs"

[[bin]]
name = "drone-client"
path = "src/bin/drone_test_client.rs"

[dev-dependencies]
ws = "0.9"
url = "2.1"

[dependencies]
hex = "0.4"
warp = "0.2"
bytes = "0.5"
smoltcp = "0.6"
rocksdb = "0.14"
failure = "0.1"
bincode = "1.2"
itertools = "0.9"
structopt = "0.3"
serde_json = "1.0"
async-trait = "0.1"
lazy_static = "1.4"

serde_cbor = "0.11"
reqwest = "0.10"
syslog_loose = "0.3"

tracing = "0.1.15"
tracing-subscriber = "0.2.5"

tokio = { version="0.2", features=["full"] }
serde = { version="1.0", features=["derive"] }
crypto = { tag = "v0.2.0", git = "https://github.com/simplestaking/tezedge" }
storage = { tag = "v0.2.0", git = "htps://github.com/simplestaking/tezedge" }
tezos_encoding = { tag = "v0.2.0", git = "https://github.com/simplestaking/tezedge" }
tezos_messages = { tag = "v0.2.0", git = "https://github.com/simplestaking/tezedge" }
networking = { tag = "v0.2.0", git = "https://github.com/simplestaking/tezedge" }