[workspace]
members = [
    "tester",
    "extractor",
    "common",

    # recorder and its bpf tools
    "tezedge-recorder",
    "bpf-recorder",
    "bpf-ring-buffer",

    #memprof and its bpf tools
    "bpf-memprof-common",
    "tezedge-memprof",
    "bpf-memprof",
]
