[package]
name = "tezedge-debugger"
version = "0.1.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
log = "0.4"
nfq = "0.2"
argh = "0.1"
bytes = "0.5"
riker = "0.4"
smoltcp = "0.6"
failure = "0.1"
rocksdb = "0.13"
crossbeam = "0.7"
serde_json = "1.0"
simple_logger = "1.6"
tokio = { version="0.2", features=["full"] }
serde = { version="1.0", features=["derive"] }
crypto = { version="*", git = "https://github.com/simplestaking/tezedge" }
storage = { version = "*", git = "htps://github.com/simplestaking/tezedge" }
networking = { version="*", git = "https://github.com/simplestaking/tezedge" }
tezos_encoding = { version="*", git = "https://github.com/simplestaking/tezedge" }
tezos_messages = { version="*", git = "https://github.com/simplestaking/tezedge" }
riker_producer = { version = "*", git = "https://github.com/Kyras/riker_producer" }