[package]
name = "tezedge_debugger"
version = "0.1.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
riker = "0.3"
packet = "0.1"
failure = "0.1"
regex = "1.3"
log = "0.4"
simple_logger = "1.6"
flume = "0.5"
hex = "0.4"
lazy_static = "1.4"
bytes = "0.5"
itertools = "0.9"
rocksdb = "0.13"
warp = "0.2"
bincode = "1.2"
serde_json = "1.0"
pnet = "0.25"
num-bigint = "0.2"
main_error = "0.1"
smoltcp = "0.6"
timeout-readwrite = "0.3"
chrono = "0.4"
serde_cbor = "0.11"
serde = { version="1.0", features=["derive"] }
tokio = { version="0.2", features=["full"] }
tun = { version = "*", git = "https://github.com/Kyras/rust-tun" }
crypto = { version="*", git = "https://github.com/simplestaking/tezedge" }
networking = { version="*", git = "https://github.com/simplestaking/tezedge" }
tezos_messages = { version="*", git = "https://github.com/simplestaking/tezedge" }
tezos_encoding = { version="*", git = "https://github.com/simplestaking/tezedge" }
storage = { version = "*", git = "htps://github.com/simplestaking/tezedge" }

[dev-dependencies]
ws = "*"
url = "2.0.0"
