rpc_port = 17732
# debugger will run syslog server on this port
syslog_port = 0
p2p_chunk_limit = 100_000
p2p_message_limit = 100_000
log_message_limit = 100_000
bpf_sniffer_path = "/tmp/bpf-sniffer.sock"

[[nodes]]
db_path = "./target/debugger_db"
# path to search identity at
identity_path = "./target/tezedge/identity.json"
# debugger expect the node will listen its p2p incoming connections on this port
# which process earliest will bind a socket on this port, will be considered as the node
# this is an inner port inside docker's virtual network of the node's container
p2p_port = 9732
