http_v2 = 17732

[[nodes]]
name = "9732"
http_v3 = 17742
db = "/tmp/volume/tezedge_debugger"
p2p = { identity = "/tmp/volume/tezedge/identity.json", port = 9732, store_limit = 10_000_000 }
log = { port = 10000, store_limit = 10_000_000 }

[[nodes]]
name = "9733"
http_v3 = 17743
db = "/tmp/volume/tezos_debugger"
p2p = { identity = "/tmp/volume/tezos/data/identity.json", port = 9733, store_limit = 10_000_000 }
log = { port = 10001, store_limit = 10_000_000 }
