bpf_sniffer_path = "/tmp/bpf-sniffer.sock"

[[nodes]]
db_path = "/tmp/volume/tezos_debugger"
identity_path = "/tmp/volume/tezos/data/identity.json"
p2p_port = 9733
syslog_port = 10001
rpc_port = 17743
