version: "3"

services:

  ocaml-debugger:
    image: simplestakingcom/tezedge-debugger:v0.1.0
    build: .
    network_mode: "service:ocaml-network"
    environment:
      - RUST_BACKTRACE=1
      # the URL should be secret, replace this placeholder with the actual slack webhooks URL
      - SLACK_HOOKS_URL=https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXXX/************************
    volumes:
      - "ocaml-shared-data:/tmp/volume"
      - /var/run:/var/run:rw
      - /proc:/proc:ro
    entrypoint: ./tezedge-debugger
    depends_on:
      - cadvisor

  ocaml-node:
    image: tezos/tezos:carthagenet
    network_mode: "service:ocaml-network"
    depends_on:
      - ocaml-debugger
    entrypoint: sh -c "sleep 5 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*'"
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:11001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "ocaml-shared-data:/var/run/tezos/node"

  ocaml-explorer:
    image: simplestakingcom/tezedge-explorer:v0.1.6
    depends_on:
      - ocaml-debugger
    ports:
      - "8080:8080"

  ocaml-network:
    image: simplestakingcom/tezedge-debugger:v0.1.0
    build: .
    ports:
      # Node specific ports
      - "11200:9732"       # node P2P port
      - "11100:8732"       # node RPC port
      # Debugger Ports must be specified on node service, because of debugger network_mode attaches
      # debugger's container to the node container, allowing it to analyze node's traffic
      - "11000:13031"      # debugger RPC port
      - "11001:13131/udp"  # debugger syslog port
    entrypoint: sleep inf

volumes:
  ocaml-shared-data:
    external: false
