version: "3"

services:
  debugger:
    image: debugger
    build: .
    network_mode: "service:node"
    volumes:
      - "shared-data:/tmp/volume"
    entrypoint: ./tezedge-debugger
  node:
    image: simplestakingcom/tezedge
    hostname: node
    ports:
      - "4927:4927"
      - "19732:9732"
      - "18732:18732"
      - "13030:13030"
      - "13031:13031"
      - "13131:13131/udp"  # Syslog port
    entrypoint: /home/appuser/tezedge/docker/compose/tezedge.sh
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://0.0.0.0:13131"  # Port must match syslog opened in 'ports' section
        syslog-format: "rfc5424micro"
    volumes:
      - "shared-data:/tmp/tezedge"

volumes:
  shared-data:
    external: false