version: "3"

services:

  ocaml-debugger:
    image: simplestakingcom/tezedge-debugger:v0.3.2
    build:
      context: .
      dockerfile: Dockerfile.dev
    privileged: true
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "ocaml-shared-data:/tmp/volume"
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
    ports:
      # Debugger Ports must be specified on node service, because of debugger network_mode attaches
      # debugger's container to the node container, allowing it to analyze node's traffic
      - "17732:17732"      # debugger RPC port
      - "11001:13131/udp"  # debugger syslog port
    entrypoint: sh -c "./cleanup_probes.sh && ./tezedge-debugger"

  ocaml-node:
    image: tezos/tezos:v7.0
    depends_on:
      - ocaml-debugger
    entrypoint: sh -c "sleep 1 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*' --rpc-addr localhost"
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:11001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "ocaml-shared-data:/var/run/tezos/node"
    ports:
      # Node specific ports
      - "11200:9732"       # node P2P port
      - "11100:8732"       # node RPC port

  ocaml-explorer:
    image: simplestakingcom/tezedge-explorer:v0.6.0
    depends_on:
      - ocaml-debugger
    ports:
      - "8080:8080"

volumes:
  ocaml-shared-data:
    external: false
