version: "3"

services:

  ocaml-debugger:
    image: simplestakingcom/tezedge-debugger:v0.3.2
    build:
      context: .
      dockerfile: Dockerfile.light
    privileged: true
    networks:
      - no-internet
      - internet
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "17732:17732"      # debugger RPC port
    volumes:
      - "ocaml-shared-data:/tmp/volume"
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
    entrypoint: sh -c "./cleanup_probes.sh && ./tezedge-debugger"

  test-node:
    build:
      context: tests/testnode
    networks:
      - no-internet
    depends_on:
      - ocaml-node
    entrypoint: sh -c "./run.sh"

  ocaml-node:
    image: tezos/tezos:v7.0
    networks:
      - no-internet
    depends_on:
      - ocaml-debugger
    entrypoint: sh -c "sleep 5 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*'"
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:11001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "ocaml-shared-data:/var/run/tezos/node"
    ports:
      - "9732:9732"

volumes:
  ocaml-shared-data:
    external: false

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
