version: "3"

services:
  rust-debugger:
    image: debugger
    build: .
    network_mode: "service:rust-node"
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "rust-shared-data:/tmp/volume"
    entrypoint: ./tezedge-debugger
  rust-node:
    image: simplestakingcom/tezedge:v0.1.0
    hostname: node
    ports:
      # Node specific ports
      - "10300:4927"        # node WS port (required only for tezedge)
      - "10200:9732"       # node P2P port
      - "10100:18732"      # node RPC port
      # Debugger Ports must be specified on node service, because of debugger network_mode attaches
      # debugger's container to the node container, allowing it to analyze node's traffic
      - "10000:13031"      # debugger RPC port
      - "10001:13131/udp"  # debugger syslog port
    entrypoint: /home/appuser/tezedge/docker/compose/tezedge.sh
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "rust-shared-data:/tmp/tezedge"

volumes:
  rust-shared-data:
    external: false