[package]
name = "bpf-sniffer-common"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@simplestaking.com>"]
edition = "2018"

[dependencies]
hex = "0.4"
passfd = "0.1"
bpf-ring-buffer = { path = "../bpf-ring-buffer", optional = true }

[features]
std = ["bpf-ring-buffer"]
