[package]
name = "bpf-ring-buffer"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@simplestaking.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
futures = "0.3"
tokio = "1.2"
smallvec = "1.6"
log = "0.4"
