[package]
name = "bpf-ring-buffer"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@simplestaking.com>"]
edition = "2018"

[dependencies]
libc = "0.2.112"
futures = "0.3.19"
tokio = { version = "1.15", features = ["net"] }
smallvec = "1.7"
log = "0.4.14"
